### ISSUE TITLE
APP用阿里加固后出现 Binary XML file line错误然后退出

### ISSUE THREAD

**Issue by xuhuan** [cpacm/SimpleSlider#8]
```
android.view.InflateException: Binary XML file line #14: Error inflating class net.cpacm.library.SimpleSliderLayout
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2760)
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:177)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:145)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5944)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183)
                                                    Caused by: android.view.InflateException: Binary XML file line #14: Error inflating class net.cpacm.library.SimpleSliderLayout
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:821)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                      
                                                       at android.support.v4.app.Fragment.performCreateView(TbsSdkJava:2184)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1298)
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(TbsSdkJava:2323)
                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(TbsSdkJava:2136)
                                                       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(TbsSdkJava:2092)
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(TbsSdkJava:1998)
                                                       at android.support.v4.app.Fragment.performStart(TbsSdkJava:2206)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1337)
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(TbsSdkJava:1523)
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1585)
                                                       at android.support.v4.app.FragmentManagerImpl.dispatchStart(TbsSdkJava:2837)
                                                       at android.support.v4.app.FragmentController.dispatchStart(TbsSdkJava:212)
                                                       at android.support.v4.app.FragmentActivity.onStart(TbsSdkJava:613)
                                                       at android.support.v7.app.AppCompatActivity.onStart(TbsSdkJava:181)
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234)
                                                       at android.app.Activity.performStart(Activity.java:6329)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2656)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2760) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:145) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5944) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183) 
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                       at java.lang.reflect.Constructor.newInstance(Native Method)
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:614)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                                                       
                                                       at android.support.v4.app.Fragment.performCreateView(TbsSdkJava:2184) 
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1298) 
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(TbsSdkJava:2323) 
                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(TbsSdkJava:2136) 
                                                       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(TbsSdkJava:2092) 
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(TbsSdkJava:1998) 
                                                       at android.support.v4.app.Fragment.performStart(TbsSdkJava:2206) 
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1337) 
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(TbsSdkJava:1523) 
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1585) 
                                                       at android.support.v4.app.FragmentManagerImpl.dispatchStart(TbsSdkJava:2837) 
                                                       at android.support.v4.app.FragmentController.dispatchStart(TbsSdkJava:212) 
                                                       at android.support.v4.app.FragmentActivity.onStart(TbsSdkJava:613) 
                                                       at android.support.v7.app.AppCompatActivity.onStart(TbsSdkJava:181) 
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234) 
                                                       at android.app.Activity.performStart(Activity.java:6329) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2656) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2760) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:145) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5944) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183) 
                                                    Caused by: android.view.InflateException: Binary XML file line #6: Error inflating class net.cpacm.library.infinite.AnimationViewPager
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:640)
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750)
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:511)
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:415)
                                                       at net.cpacm.library.SimpleSliderLayout.init(TbsSdkJava)
                                                       at net.cpacm.library.SimpleSliderLayout.<init>(TbsSdkJava)
                                                       at java.lang.reflect.Constructor.newInstance(Native Method) 
                                                       at java.lang.reflect.Constructor.newInstance(Constructor.java:288) 
                                                       at android.view.LayoutInflater.createView(LayoutInflater.java:614) 
                                                       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:750) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:813) 
                                                       at android.view.LayoutInflater.rInflate(LayoutInflater.java:821) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:511) 
                                                       at android.view.LayoutInflater.inflate(LayoutInflater.java:415) 
                                                     
                                                       at android.support.v4.app.Fragment.performCreateView(TbsSdkJava:2184) 
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1298) 
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentsToInvisible(TbsSdkJava:2323) 
                                                       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(TbsSdkJava:2136) 
                                                       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(TbsSdkJava:2092) 
                                                       at android.support.v4.app.FragmentManagerImpl.execPendingActions(TbsSdkJava:1998) 
                                                       at android.support.v4.app.Fragment.performStart(TbsSdkJava:2206) 
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1337) 
                                                       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(TbsSdkJava:1523) 
                                                       at android.support.v4.app.FragmentManagerImpl.moveToState(TbsSdkJava:1585) 
                                                       at android.support.v4.app.FragmentManagerImpl.dispatchStart(TbsSdkJava:2837) 
                                                       at android.support.v4.app.FragmentController.dispatchStart(TbsSdkJava:212) 
                                                       at android.support.v4.app.FragmentActivity.onStart(TbsSdkJava:613) 
                                                       at android.support.v7.app.AppCompatActivity.onStart(TbsSdkJava:181) 
                                                       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1234) 
                                                       at android.app.Activity.performStart(Activity.java:6329) 
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2656) 
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2760) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:177) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:145) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5944) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1388) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1183) 
                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                   	at java.lang.reflect.Constructor.newInstance(
```

没加固前正常,加固后出现这个问题,然后app进不去,进去就崩掉退出.用的是最新1.0.3版.
@cpacm

**Comment by cpacm** [comment]
先说结论：
引起问题是的 AnimationViewPager 下的initViewPager() 方法，因为 Viewpager 里面也有这个方法，所以加固完之后就找不到原来的initViewPager() 方法。
但是用 360 加固是没有任何问题的，用阿里加固就会出现这个问题。

稍候我会把 AnimationViewPager 下的initViewPager() 方法改个名字，应该就没问题了。
@xuhuan

**Comment by xuhuan** [comment]
@cpacm 回应和解决挺快的,谢谢!
